/* Sanctuaire Iwate Oracle — voile, hymne, cadre modal, lucioles (ex-inline index.html) */
function enterSanctuary(){document.getElementById('veil').classList.add('hide');var a=document.getElementById('hymn');if(a){a.volume=0.5;var p=a.play();if(p&&p.catch){p.catch(function(){/* pas encore de musique, le sanctuaire reste silencieux */});}var b=document.getElementById('sndBtn');if(b){b.textContent='🔊';}}}
function toggleSnd(){var a=document.getElementById('hymn');var b=document.getElementById('sndBtn');if(!a||!b)return;if(a.paused){a.volume=0.5;var p=a.play();if(p&&p.catch){p.catch(function(){});}b.textContent='🔊';}else{a.pause();b.textContent='🔇';}}
var _orb=document.getElementById('topOrb');if(_orb){_orb.addEventListener('click',function(){openFrame('omikuji.html','Omikuji');});}
/* — titres robustes + deep-link hash (fix Nova 08/10) — */
var FRAME_URL={sanctuaire:'iwate.html',iwate:'iwate.html',voix:'iwate2.html',iwate2:'iwate2.html',traversee:'iwate3.html',iwate3:'iwate3.html',rencontre:'iwate3.html',omikuji:'omikuji.html',question:'question.html',consultation:'iwate3.html',packs:'iwate3.html',infos:'infos.html',seance:'seance.html'};
var FRAME_TITLE={sanctuaire:'Iwate 序',iwate:'Iwate 序',voix:'Iwate 破',iwate2:'Iwate 破',traversee:'Iwate 急',iwate3:'Iwate 急',rencontre:'Iwate 急',omikuji:'Omikuji 零',question:'Question 壱',consultation:'Iwate 急',packs:'Iwate 急',infos:'Infos 参肆伍',seance:'Séance 陸'};
function keyFromUrl(url){for(var k in FRAME_URL){if(FRAME_URL[k]===url)return k;}return null;}
function openFrame(url,title,skipHash){var key=keyFromUrl(url);var label=title||(key&&FRAME_TITLE[key])||'Sanctuaire';document.getElementById('frameTitle').textContent=label;document.getElementById('framePage').src=url;document.getElementById('fModal').classList.add('on');document.body.style.overflow='hidden';if(!skipHash&&key){var want='#'+(key==='packs'?'consultation':key);if(location.hash!==want){location.hash=want;}}return false;}
function closeFrame(skipHash){document.getElementById('fModal').classList.remove('on');document.getElementById('framePage').src='about:blank';document.body.style.overflow='';if(!skipHash&&location.hash){history.back();}}
function liveFrameFile(fr){var href='';try{href=fr.contentWindow.location.href||'';}catch(e){}var file=(href.split('?')[0].split('/').pop()||'');if(!file||file==='about:blank'||file==='blank'){var a=fr.getAttribute('src')||'';file=a.split('?')[0].split('/').pop();}return file;}
document.getElementById('framePage').addEventListener('load',function(){try{var key=keyFromUrl(liveFrameFile(this));if(key&&FRAME_TITLE[key]){document.getElementById('frameTitle').textContent=FRAME_TITLE[key];return;}var d=this.contentDocument||this.contentWindow.document;var t=(d.title||'').split('—');var tail=t[t.length-1].trim().split(' ');var name=tail[tail.length-1];if(name){document.getElementById('frameTitle').textContent=name;}}catch(e){/* autre origine, on garde le titre robuste */}});
document.addEventListener('keydown',function(e){if(e.key==='Escape')closeFrame();});
/* hashchange = Back mobile ferme le cadre, partage index.html#consultation */
window.addEventListener('hashchange',function(){var h=(location.hash||'').replace('#','');var modal=document.getElementById('fModal');var fr=document.getElementById('framePage');if(!h){if(modal.classList.contains('on'))closeFrame(true);return;}if(FRAME_URL[h]){if(modal.classList.contains('on')&&(liveFrameFile(fr)===FRAME_URL[h]||fr.getAttribute('src')===FRAME_URL[h]))return;openFrame(FRAME_URL[h],FRAME_TITLE[h],true);}});
(function(){var h=(location.hash||'').replace('#','');if(h&&FRAME_URL[h]){openFrame(FRAME_URL[h],FRAME_TITLE[h],true);}})();
(function(){var c=document.getElementById('fx');if(!c)return;var x=c.getContext('2d'),P=[],mx=-999,my=-999;function rs(){c.width=innerWidth;c.height=innerHeight;}rs();addEventListener('resize',rs);addEventListener('mousemove',function(e){mx=e.clientX;my=e.clientY;});var g=['✨','🌸','✦','🕯️'];for(var i=0;i<45;i++){P.push({x:Math.random()*innerWidth,y:Math.random()*innerHeight,s:8+Math.random()*14,vx:(Math.random()-.5)*.4,vy:-.2-Math.random()*.5,g:g[i%4],a:.3+Math.random()*.6});}
(function loop(){x.clearRect(0,0,c.width,c.height);for(var i=0;i<P.length;i++){var p=P[i];var dx=p.x-mx,dy=p.y-my,d=Math.sqrt(dx*dx+dy*dy);if(d<110&&d>1){p.x+=dx/d*1.2;p.y+=dy/d*1.2;}p.x+=p.vx;p.y+=p.vy;if(p.y<-20){p.y=innerHeight+20;p.x=Math.random()*innerWidth;}x.globalAlpha=p.a;x.font=p.s+'px serif';x.fillText(p.g,p.x,p.y);}x.globalAlpha=1;requestAnimationFrame(loop);})();})();
