/* Sanctuaire Iwate Oracle — voile, hymne, cadre modal, lucioles (ex-inline index.html) */
function enterSanctuary(){document.getElementById('veil').classList.add('hide');var a=document.getElementById('hymn');if(a){a.volume=0.5;var p=a.play();if(p&&p.catch){p.catch(function(){/* pas encore de musique, le sanctuaire reste silencieux */});}var b=document.getElementById('sndBtn');if(b){b.textContent='🔊';}}}
function toggleSnd(){var a=document.getElementById('hymn');var b=document.getElementById('sndBtn');if(!a||!b)return;if(a.paused){a.volume=0.5;var p=a.play();if(p&&p.catch){p.catch(function(){});}b.textContent='🔊';}else{a.pause();b.textContent='🔇';}}
var _orb=document.getElementById('topOrb');if(_orb){_orb.addEventListener('click',function(){openFrame('omikuji.html','Omikuji');});}
function openFrame(url,title){document.getElementById('frameTitle').textContent=title||'Sanctuaire';document.getElementById('framePage').src=url;document.getElementById('fModal').classList.add('on');document.body.style.overflow='hidden';return false;}
function closeFrame(){document.getElementById('fModal').classList.remove('on');document.getElementById('framePage').src='about:blank';document.body.style.overflow='';}
document.getElementById('framePage').addEventListener('load',function(){try{var d=this.contentDocument||this.contentWindow.document;var t=(d.title||'').split('—');var tail=t[t.length-1].trim().split(' ');var name=tail[tail.length-1];if(name){document.getElementById('frameTitle').textContent=name;}}catch(e){/* autre origine, on garde l'ancien titre */}});
document.addEventListener('keydown',function(e){if(e.key==='Escape')closeFrame();});
(function(){var c=document.getElementById('fx');if(!c)return;var x=c.getContext('2d'),P=[],mx=-999,my=-999;function rs(){c.width=innerWidth;c.height=innerHeight;}rs();addEventListener('resize',rs);addEventListener('mousemove',function(e){mx=e.clientX;my=e.clientY;});var g=['✨','🌸','✦','🕯️'];for(var i=0;i<45;i++){P.push({x:Math.random()*innerWidth,y:Math.random()*innerHeight,s:8+Math.random()*14,vx:(Math.random()-.5)*.4,vy:-.2-Math.random()*.5,g:g[i%4],a:.3+Math.random()*.6});}
(function loop(){x.clearRect(0,0,c.width,c.height);for(var i=0;i<P.length;i++){var p=P[i];var dx=p.x-mx,dy=p.y-my,d=Math.sqrt(dx*dx+dy*dy);if(d<110&&d>1){p.x+=dx/d*1.2;p.y+=dy/d*1.2;}p.x+=p.vx;p.y+=p.vy;if(p.y<-20){p.y=innerHeight+20;p.x=Math.random()*innerWidth;}x.globalAlpha=p.a;x.font=p.s+'px serif';x.fillText(p.g,p.x,p.y);}x.globalAlpha=1;requestAnimationFrame(loop);})();})();
